name: Upload

on: push

jobs:
  upload:
    name: Upload file
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v2

      - name: Upload file example
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            file_example_JPG_100kB.jpeg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
